language: julia
os:
  - linux
  - osx
julia:
  - 1.1
notifications:
  email: true
script:
  - julia -e 'using Pkg; Pkg.add("Mimi")'
  - julia -e 'using Pkg; Pkg.add("CSVFiles")'
  - julia -e 'using Pkg; Pkg.add("Query")'
  - julia -e 'using Pkg; Pkg.add("DataFrames")'
  - julia -e 'using Pkg; Pkg.add("Distributions")'
  - julia -e 'using Pkg; Pkg.add("Query")'
  - julia -e 'using Pkg; Pkg.add("Missings")'
  - julia --code-coverage=user test/runtests.jl
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
